### ISSUE TITLE
Height of div allows for scroll bar to start floating away from the bottom

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#12]
When all channels are having what looks to be less than 4 (with my window size) videos left, the scroll bar starts moving up to match the bottom of the channels. 
![image](https://user-images.githubusercontent.com/13324054/66327003-0a120f80-e8f8-11e9-87e0-e616d6cd9ef7.png)

**Comment by yamalight** [comment]
Making it full-height would definitely make it look better. Will adjust!
