### ISSUE TITLE
Make whole div of youtube video clickable

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#14]
Might I suggest having the whole div clickable instead of just the text? Comparison of what it is now vs what you could do:

![image](https://user-images.githubusercontent.com/13324054/66569826-58165580-eb3a-11e9-954d-ce78c170638e.png)
![image](https://user-images.githubusercontent.com/13324054/66569687-12598d00-eb3a-11e9-9849-616eb64857bf.png)

**Comment by yamalight** [comment]
Sure, that makes sense 🤔

**Comment by fegkay15** [comment]
I did notice that what I edited does affect the mark watched button from appearing, however, I was going to suggest having a static mark watched button anyways similar to the eye icon from video deck since it can cause the image to move around, and if it's the last unwatched video, the text moves around too:
![hover](https://user-images.githubusercontent.com/13324054/66570885-7a10d780-eb3c-11e9-9f0c-d3066f55de32.gif)

**Comment by yamalight** [comment]
yep, that part definitely needs some love. was too lazy to make it look nice

**Comment by yamalight** [comment]
Both things should be addressed in [v1.0-pre6](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre6). Feel free to re-open if that's not the case :)
