### ISSUE TITLE
Livestreams causing issues

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#16]
Had an issue where a `Cannot read property 'simpleText' of undefined` error appeared when I reach 34/73 channels. I deminified the js code and found it to be this line where it gets published time of a video for it to show in youtube control: `publishedTime: e.publishedTimeText.simpleText`. I wasn't sure why, so I added a console.log to tell me which video it was and I found it to be an active livestream, which obviously doesn't have a publish time yet. And sure enough, when the stream stopped, youtube control no longer had an issue.

**Comment by yamalight** [comment]
Oh, man, I haven't even though about livestreams! Nice catch 😃 
Did you happen to save the JSON dump you've made? That'd help a ton in identifying livestreams and displaying them accordingly 🤔

**Comment by fegkay15** [comment]
Yeah, here's one of an active livestream: 
[console.log](https://github.com/yamalight/youtube-control/files/3720664/console.log)

**Comment by yamalight** [comment]
@fegkay15 this is great, thank you!

**Comment by fegkay15** [comment]
Same thing also happening with scheduled videos/streams:
![image](https://user-images.githubusercontent.com/13324054/66711884-6646ba80-ed62-11e9-8755-d009b2d77962.png)

Log of that scheduled video: 
[console2.log](https://github.com/yamalight/youtube-control/files/3721492/console2.log)

**Comment by yamalight** [comment]
@fegkay15 interesting. thanks for the dump! will try to put out an update that fixes this in the next few days

**Comment by yamalight** [comment]
Should be fixed in [v1.0-pre6](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre6). Feel free to re-open if that's not the case :)
