### ISSUE TITLE
Cannot read property 'filter' of undefined on fresh install

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#18]
On a fresh install, just sits at 0/0 channels:
![image](https://user-images.githubusercontent.com/13324054/66717948-4fc55100-edac-11e9-8dd2-d0a6851eaca8.png)

![image](https://user-images.githubusercontent.com/13324054/66717851-98c8d580-edab-11e9-9057-9cd1a9248d92.png)

**Comment by yamalight** [comment]
Should be fixed in [v1.0-pre7](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre7)
