### ISSUE TITLE
premierTime is not defined error on existing extension

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#19]
I get this error after it has loaded through all 73 of my channels (I replaced the files in the same unpacked directory I had set in chrome to keep my channels) and it stays just a blank white screen: 
![image](https://user-images.githubusercontent.com/13324054/66718004-fc073780-edac-11e9-9f4c-9075a997aced.png)

`(e => e.publishedTime ? 'Published ${e.publishedTime}' : e.isLivestream ? "Livestream" : e.premierTime ? 'Premiers at ${new Date(premierTime).toLocaleString()}' : void 0)(e)))))))`

**Comment by yamalight** [comment]
Should be fixed in [v1.0-pre7](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre7)
