### ISSUE TITLE
Stuck at Loading Channels List

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#2]
After loading it as an unpacked extension, I try to pull it up and just sits at "loading channels list" with no way for me to remove it and attempt to add any channels in the first place.
![image](https://user-images.githubusercontent.com/13324054/66267199-49f3cc80-e7fc-11e9-8132-fc8b709b9d41.png)

**Comment by fegkay15** [comment]
![image](https://user-images.githubusercontent.com/13324054/66267255-9808d000-e7fc-11e9-8f61-49356cbd15c7.png)

**Comment by fegkay15** [comment]
Clearing my cookies for youtube allowed for it to work.

**Comment by fegkay15** [comment]
The issue is being caused by the use of this extension to go back to youtube's old layout which edits the cookies for youtube: https://chrome.google.com/webstore/detail/youtube-classic-restore-y/aooobjmnokciopfgejdlbnklafighoaj

**Comment by yamalight** [comment]
@fegkay15 thanks for investigating!
I am basically parsing youtube html, so it'll only work with "modern" version.
I need to add some error handling and messages to clarify this in the extension itself 🤔

**Comment by fegkay15** [comment]
@yamalight No problem. I was still using the old layout due to an old extension I had that adds tons of features to the youtube ui, however it was updated 3 days ago to use the new ui finally. So i'm able to switch over to the new ui and use your extension, so that's good. Had a question though, is there a way that it could be made to have maybe a checkbox or a setting to have the videos open to youtube rather than have them embeded in your extension similar to what videodeck allowed? Those ui add-on features I was talking about are only usable on youtube itself.

**Comment by yamalight** [comment]
@fegkay15 v1.0-pre2 is out in releases, should now correctly display error when using old layout.

You can open videos in new tab my middle-clicking on them - it's still just an `<a href>`, just intercepted by default. If that's not good enough - I can add a settings thing too 🤔

**Comment by fegkay15** [comment]
It's up to you. You're the dev providing a free product, so I don't get a true choice. lol.

**Comment by yamalight** [comment]
@fegkay15 well, the question in this case - is middle-click good enough? 😛

**Comment by fegkay15** [comment]
It's good enough. However, that option to auto open to youtube would be nice. 😄

**Comment by yamalight** [comment]
@fegkay15 got it. created a new issue for that, will close this one now :)
