### ISSUE TITLE
Update screenshot with new dark themed one

### ISSUE THREAD

**Issue by yamalight** [yamalight/youtube-control#21]
Currently we have an outdated screenshot in readme 🤔

**Comment by fegkay15** [comment]
![image](https://user-images.githubusercontent.com/13324054/66852231-7f11c480-ef4a-11e9-9897-d4efacc3ba11.png)

**Comment by yamalight** [comment]
@fegkay15 this is great! would it be possible for you to send a PR with this? 😊
