### ISSUE TITLE
Error loading channel that has youtube originals videos due to no view count?

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#3]
Added Vsauce which was the first channel I added that has youtube originals content on it. Error happens when it attempts to get view count text:
![image](https://user-images.githubusercontent.com/13324054/66267780-8676f680-e803-11e9-8c6f-16e2141c3173.png)
![image](https://user-images.githubusercontent.com/13324054/66267782-8c6cd780-e803-11e9-865b-890e465c6eb1.png)
![image](https://user-images.githubusercontent.com/13324054/66267793-b1614a80-e803-11e9-9e8e-670e047f194a.png)

**Comment by yamalight** [comment]
should be fixed in v1.0-pre3 release
