### ISSUE TITLE
Add settings screen

### ISSUE THREAD

**Issue by yamalight** [yamalight/youtube-control#4]
Basic settings screen would be nice to have.
Toggles that could be there:
- [x] % to consider "watched" (hardcoded right now)
- [x] open links in new tab instead of modal (see https://github.com/yamalight/youtube-control/issues/2#issuecomment-538731027)
- [x] no column wrap mode

**Comment by fegkay15** [comment]
Don't want to make it seem like I'm requesting a lot, and I also don't know what is planned, but any chance an option could be made to have channels lined up horizontally and scrolled horizontally as an alternative to the vertical scrolling as it is now? That would be the last thing left afaik to make mission control identical to how I had my Video Deck configured.

**Comment by yamalight** [comment]
@fegkay15 Sure, that should be relatively easy to do. I haven't seen / used that in video deck though. Do you have a screenshot for me, so I'm 100% sure I understand that correctly? 😅 

Also, do keep those requests coming. those are some good features 😃

**Comment by fegkay15** [comment]
Only thing I have to show is the [original launch video of video deck](https://www.youtube.com/watch?v=20NDj-y5ND8) and they use horizontal scrolling in the video up until 43 seconds when they change it to vertical. The video might also help you bring mission control (youtube control? Can't tell what you're calling it as I see both names) to parity with video deck.

**Comment by fegkay15** [comment]
Oh, also, dark mode setting.

**Comment by yamalight** [comment]
@fegkay15 ahhh, now i get it. totally misunderstood first time 😂 yep, that should be easy to do

**Comment by fegkay15** [comment]
Any way to add multiple channels at once, rather than go one by one?

**Comment by yamalight** [comment]
Not yet, but that's a good suggestion - please open a new ticket for it :)
