### ISSUE TITLE
Cannot read property 'thumbnails' of undefined

### ISSUE THREAD

**Issue by Jgonaz** [yamalight/youtube-control#5]
Hi! I got stuck on the Loading channels list screen.

![image](https://user-images.githubusercontent.com/19613088/66291019-01faa580-e8e1-11e9-9035-2fde1e3438cf.png)

**Comment by yamalight** [comment]
@Jgonaz thanks for reporting this. Could you tell me when that happens / what channel is loading if possible?

**Comment by Jgonaz** [comment]
I really don't know, it happens to me when I open the extension.

I deleted the cookies on my browser and the error changed.

"TypeError: Cannot read property 'thumbnails' of undefined"

**Comment by yamalight** [comment]
@Jgonaz so you haven't added any channels yet? just launched the extension? 🤔

**Comment by Jgonaz** [comment]
Exactly :(

**Comment by yamalight** [comment]
@Jgonaz got it! would it be possible to share a list of your subscriptions?

**Comment by Jgonaz** [comment]
For sure, but I'm subscribed to more than 1k channels 😝 

Thanks.

[subscription_manager.zip](https://github.com/yamalight/youtube-control/files/3696995/subscription_manager.zip)

**Comment by yamalight** [comment]
@Jgonaz holy crap, hahaha! thank you, will investigate 😅

**Comment by Jgonaz** [comment]
Thanks a lot! I also use this extensions for youtube in Chrome.

https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle
https://chrome.google.com/webstore/detail/audio-only-youtube/pkocpiliahoaohbolmkelakpiphnllog
https://chrome.google.com/webstore/detail/images-onoff/nfmlhilnjccdggifdbhnhkffmjgalbgg?hl=en&gl=001

**Comment by yamalight** [comment]
@Jgonaz those shouldn't in theory interfere. I think I've found the bug. Will release an update with a fix later today :)

**Comment by yamalight** [comment]
Should be fixed in https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre4
Feel free to re-open if that's not the case.
