### ISSUE TITLE
Add dark mode (use by default?)

### ISSUE THREAD

**Issue by yamalight** [yamalight/youtube-control#7]
See https://github.com/yamalight/youtube-control/issues/4#issuecomment-538736871

**Comment by fegkay15** [comment]
Suggestion on the color palette to use:

All Text: `#FFFFFF`
Top Bar: `#212121`
Background: `#303030`
Border: `#696969`
Mark All Watched Button: `#303030`
Mark All Watched Button (Hover): `#424242`


![image](https://user-images.githubusercontent.com/13324054/66731220-4972bb80-ee24-11e9-8046-bea39ced5dca.png)

Referenced Material Design Dark Theme: 
![image](https://user-images.githubusercontent.com/13324054/66731568-01ed2f00-ee26-11e9-9ee7-478d18dfab89.png)

**Comment by yamalight** [comment]
@fegkay15 this looks great, thank you!

**Comment by yamalight** [comment]
Shipped in [v1.0-pre8](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre8)
I ended up using default tailwindcss colors for easier adjustments - let me know what you think :)

**Comment by fegkay15** [comment]
Looks good! Thank you. I also wanted to thank you for being such a supportive dev with our requests and bugs. Not many people would be this supportive
