### ISSUE TITLE
Stuck on Loading Channels list

### ISSUE THREAD

**Issue by LoadsOfMana** [yamalight/youtube-control#8]
worked great for a day, now gets stuck here every time i try to open it
![image](https://user-images.githubusercontent.com/50811266/66315499-ca80fe80-e8ca-11e9-9fa3-2f06f30f3074.png)

**Comment by yamalight** [comment]
@LoadsOfMana could you please share the console output?
Potentially it's same as #5 and I've fixed that (will publish a build with a fix soon-ish)

**Comment by yamalight** [comment]
Please try [v1.0-pre5](https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre5) and let me know if it still happens

**Comment by RafaelSaintsB** [comment]
I have the same problem on v1.0-pre5.

![image](https://user-images.githubusercontent.com/56271212/66333835-2faa1380-e90e-11e9-820b-06d8d6f1f984.png)

**Comment by RafaelSaintsB** [comment]
I tried now on pre4 and worked.

**Comment by LoadsOfMana** [comment]
seems to have fixed it.

**Comment by yamalight** [comment]
Great, closing it
