### ISSUE TITLE
Horizontal scroll layout, first channel outside of left edge of the browser view

### ISSUE THREAD

**Issue by fegkay15** [yamalight/youtube-control#9]
As title and image suggests. Sometimes if I add another channel it aligns itself correctly, but adding another channel may or may not cause the issue again.
![image](https://user-images.githubusercontent.com/13324054/66321219-3cb70a80-e8ee-11e9-8f27-d1b6fdf2414f.png)

**Comment by yamalight** [comment]
Yep, could reproduce. Will try to figure out wtf 🤔

**Comment by yamalight** [comment]
@fegkay15 should be fixed in https://github.com/yamalight/youtube-control/releases/tag/v1.0-pre5
